"""Convert GPUMODE/KernelBook rows into KernelBench-style problem source.

KernelBook's ``python_code`` defines an nn.Module under its *original* name
(e.g. ``LinearEmbedding``) and a ``get_init_inputs()`` that returns
``[args_list, kwargs_dict]``. KernelBench's evaluator instead requires:

  * a class named exactly ``Model``,
  * ``get_inputs() -> list`` (positional forward args), and
  * ``get_init_inputs() -> list``, consumed positionally as ``Model(*get_init_inputs())``.

This module bridges the gap with a single :func:`convert_row` that returns a
runnable KernelBench-style source string, plus :func:`smoke_test` to filter rows
whose reference does not even run in eager mode.
"""

import ast
import inspect
import re

_SELF = object()  # placeholder bound to the `self` parameter during signature binding
_MISSING = object()  # marks an __init__ param left at its default during flattening

# A short header appended-after marker so the conversion is easy to spot/debug.
_BANNER = "\n\n# --- KernelBench adapter (auto-generated by kernelbook_convert) ---\n"


class ConversionError(Exception):
    """Raised when a KernelBook row cannot be turned into a valid problem."""


def _is_valid_identifier(name: str) -> bool:
    return bool(name) and name.isidentifier()


def _literalizable(value) -> bool:
    """True if ``value`` round-trips through repr / ast.literal_eval.

    Only plain literals (ints, floats, str, bool, None, and lists/tuples/dicts
    thereof) qualify — anything else (tensors, custom objects) forces the
    runtime-bake fallback.
    """
    try:
        return ast.literal_eval(repr(value)) == value
    except Exception:
        return False


def _normalize_init(raw) -> tuple[list, dict]:
    """Normalize KernelBook ``get_init_inputs()`` output to ``(args, kwargs)``.

    KernelBook returns ``[args_list, kwargs_dict]`` but a few rows return a plain
    positional list — handle both.
    """
    if (
        isinstance(raw, (list, tuple))
        and len(raw) == 2
        and isinstance(raw[0], (list, tuple))
        and isinstance(raw[1], dict)
    ):
        return list(raw[0]), dict(raw[1])
    if isinstance(raw, (list, tuple)):
        return list(raw), {}
    raise ConversionError(f"unexpected get_init_inputs() shape: {type(raw).__name__}")


def _flatten_to_positional(cls, args: list, kwargs: dict):
    """Return an all-positional arg list equivalent to ``cls(*args, **kwargs)``.

    Returns ``None`` when the call cannot be expressed positionally (``*args`` /
    ``**kwargs`` inits, or a defaulted param skipped before a later supplied one).
    """
    try:
        sig = inspect.signature(cls.__init__)
        bound = sig.bind(_SELF, *args, **kwargs)
    except (TypeError, ValueError):
        return None

    positional = []
    for name, p in sig.parameters.items():
        if name == "self":
            continue
        if p.kind in (p.VAR_POSITIONAL, p.VAR_KEYWORD):
            if bound.arguments.get(name):  # actually used → not expressible positionally
                return None
            continue
        positional.append(bound.arguments.get(name, _MISSING))

    while positional and positional[-1] is _MISSING:  # trailing defaults are fine to drop
        positional.pop()
    if any(x is _MISSING for x in positional):  # interior gap → not positional
        return None
    return positional


def convert_row(python_code: str, module_name: str) -> str:
    """Return KernelBench-style source for one KernelBook row.

    Strategy (A): when the original init is expressible as pure positional
    literals, alias ``Model = <module_name>`` and emit a flat-positional
    ``get_init_inputs()`` — byte-compatible with a hand-written KernelBench
    problem. Aliasing (rather than renaming the class body) keeps any internal
    ``super(<module_name>, self)`` references valid.

    Strategy (B) fallback: keep the original class verbatim and add a no-arg
    ``Model`` subclass that bakes the captured args/kwargs, with
    ``get_init_inputs()`` returning ``[]``. Robust for non-literal init args.
    """
    if not _is_valid_identifier(module_name):
        raise ConversionError(f"module_name {module_name!r} is not a valid identifier")
    if not re.search(rf"\bclass\s+{re.escape(module_name)}\b", python_code):
        raise ConversionError(f"class {module_name!r} not found in python_code")

    # Execute the original to read its declared init inputs.
    ns: dict = {}
    try:
        exec(compile(python_code, "<kernelbook_row>", "exec"), ns)
    except Exception as e:  # noqa: BLE001 - surface any import/exec failure to caller
        raise ConversionError(f"python_code failed to exec: {e}") from e

    if "get_init_inputs" not in ns:
        raise ConversionError("python_code does not define get_init_inputs()")
    if "get_inputs" not in ns:
        raise ConversionError("python_code does not define get_inputs()")
    if module_name not in ns:
        raise ConversionError(f"{module_name!r} not defined after exec")

    args, kwargs = _normalize_init(ns["get_init_inputs"]())

    # Strategy A: flatten the init to all-positional literals (binding kwargs against
    # the __init__ signature) -> a native-looking KernelBench problem.
    flat = _flatten_to_positional(ns[module_name], args, kwargs)
    if flat is not None and all(_literalizable(a) for a in flat):
        positional = ", ".join(repr(a) for a in flat)
        return (
            python_code.rstrip()
            + _BANNER
            + f"Model = {module_name}\n\n"
            + "def get_init_inputs():\n"
            + f"    return [{positional}]\n"
        )

    # Strategy B: bake captured args/kwargs into a no-arg Model subclass.
    return (
        python_code.rstrip()
        + _BANNER
        + "_kb_raw_init = get_init_inputs()\n"
        + "if (isinstance(_kb_raw_init, (list, tuple)) and len(_kb_raw_init) == 2\n"
        + "        and isinstance(_kb_raw_init[0], (list, tuple)) and isinstance(_kb_raw_init[1], dict)):\n"
        + "    _KB_ARGS, _KB_KWARGS = list(_kb_raw_init[0]), dict(_kb_raw_init[1])\n"
        + "else:\n"
        + "    _KB_ARGS, _KB_KWARGS = list(_kb_raw_init), {}\n\n"
        + f"class Model({module_name}):\n"
        + "    def __init__(self):\n"
        + "        super().__init__(*_KB_ARGS, **_KB_KWARGS)\n\n"
        + "def get_init_inputs():\n"
        + "    return []\n"
    )


def smoke_test(converted_src: str, device: str = "cuda") -> tuple[bool, str]:
    """Instantiate the converted ``Model`` and run one eager forward.

    Returns ``(ok, reason)``. ``reason`` is empty on success, otherwise a short
    diagnostic. Requires a working torch install (and a CUDA device when
    ``device`` is a CUDA device).
    """
    import torch  # local import so the converter is usable without torch present

    ns: dict = {}
    try:
        exec(compile(converted_src, "<converted>", "exec"), ns)
    except Exception as e:  # noqa: BLE001
        return False, f"exec failed: {e}"

    for required in ("Model", "get_inputs", "get_init_inputs"):
        if required not in ns:
            return False, f"missing {required}"

    def _to_device(obj):
        if isinstance(obj, torch.Tensor):
            return obj.to(device)
        if isinstance(obj, (list, tuple)):
            return type(obj)(_to_device(o) for o in obj)
        return obj

    try:
        init_inputs = ns["get_init_inputs"]()
        model = ns["Model"](*init_inputs).to(device)
        model.eval()
        inputs = _to_device(ns["get_inputs"]())
        with torch.no_grad():
            model(*inputs)
    except Exception as e:  # noqa: BLE001
        return False, f"forward failed: {type(e).__name__}: {e}"

    return True, ""
