"""Convert GPUMODE/KernelBook rows into KernelBench-style problem source.

KernelBook's ``python_code`` defines an nn.Module under its *original* name
(e.g. ``LinearEmbedding``) and a ``get_init_inputs()`` that returns
``[args_list, kwargs_dict]``. KernelBench's evaluator instead requires:

  * a class named exactly ``Model``,
  * ``get_inputs() -> list`` (positional forward args), and
  * ``get_init_inputs() -> list``, consumed positionally as ``Model(*get_init_inputs())``.

This module bridges the gap with a single :func:`convert_row` that returns a
runnable KernelBench-style source string, plus :func:`smoke_test` to filter rows
whose reference does not even run in eager mode.
"""

import ast
import inspect
import re
import signal
import time
from dataclasses import dataclass, field

_SELF = object()  # placeholder bound to the `self` parameter during signature binding
_MISSING = object()  # marks an __init__ param left at its default during flattening

# A short header appended-after marker so the conversion is easy to spot/debug.
_BANNER = "\n\n# --- KernelBench adapter (auto-generated by kernelbook_convert) ---\n"

# torch tensor-creators whose *first positional arg* is the shape (list/tuple or
# bare int varargs). These are the only int literals we touch when up-scaling, so
# we never disturb dtypes, fill values, randint bounds, or `torch.tensor([...])` data.
_SHAPE_AT_ARG0 = frozenset({"rand", "randn", "zeros", "ones", "empty", "full"})

# Default per-rank target edge length for KernelBook's placeholder dim. Chosen so
# every input tensor lands in a "modest/safe" ~5-8M-element band regardless of rank
# (S**rank): big enough to leave the kernel-launch-overhead regime on an A100/H100,
# small enough to keep eval cheap and avoid OOM. Tunable via ScaleConfig / CLI.
DEFAULT_SCALE_BY_RANK = {1: 2048, 2: 2048, 3: 160, 4: 48, 5: 24}
DEFAULT_HIGHER_RANK_SCALE = 16  # rank >= 6 (rare) — keep it tiny


@dataclass
class ScaleConfig:
    """How to up-scale KernelBook's placeholder dims into GPU-meaningful sizes.

    Only integer literals equal to ``placeholder`` (KernelBook's magic ``4``) are
    ever rewritten, so genuinely meaningful dims (``3`` RGB channels, ``64`` spatial,
    ``784`` MNIST) are preserved untouched. A single target ``S`` is computed per row
    from the *max* input-tensor rank and applied uniformly to every placeholder dim
    in both ``get_inputs`` shapes and ``get_init_inputs`` — which keeps the dataset's
    built-in shape coupling (e.g. ``hidden_size`` == input's last dim) intact.
    """

    placeholder: int = 4
    mode: str = "uniform"  # "uniform" | "batch-only" | "off"
    scale_by_rank: dict = field(default_factory=lambda: dict(DEFAULT_SCALE_BY_RANK))
    higher_rank_scale: int = DEFAULT_HIGHER_RANK_SCALE
    batch_target: int = 2048  # leading-dim target for mode="batch-only"
    factor: float = 1.0  # global multiplier (the smoke-test fallback ladder lowers this)

    def target_for_rank(self, rank: int) -> int:
        """Scaled edge length for a placeholder dim in a max-rank-``rank`` row."""
        base = self.scale_by_rank.get(rank, self.higher_rank_scale)
        return max(self.placeholder, int(round(base * self.factor)))


class ConversionError(Exception):
    """Raised when a KernelBook row cannot be turned into a valid problem."""


def _func_name(call: ast.Call) -> str | None:
    """Return the called function's bare name: ``torch.rand`` / ``rand`` -> ``rand``."""
    f = call.func
    if isinstance(f, ast.Attribute):
        return f.attr
    if isinstance(f, ast.Name):
        return f.id
    return None


def _shape_elts(call: ast.Call) -> list | None:
    """Return the mutable list of element-nodes describing ``call``'s shape, or None.

    Handles ``torch.rand([..])`` / ``torch.rand((..))`` / ``torch.rand(4, 4)`` and
    ``torch.randint(lo, hi, [..])``. Mutating the returned list rewrites the shape
    in place; ``None`` means this call has no recognizable integer shape.
    """
    name = _func_name(call)
    if name in _SHAPE_AT_ARG0 and call.args:
        a0 = call.args[0]
        if isinstance(a0, (ast.List, ast.Tuple)):
            return a0.elts
        # bare int varargs, e.g. torch.rand(4, 4, 4) — but not full(size, fill_value)
        if name != "full" and all(
            isinstance(a, ast.Constant) and isinstance(a.value, int) for a in call.args
        ):
            return call.args
    if name == "randint":
        size = next((kw.value for kw in call.keywords if kw.arg == "size"), None)
        if size is None and len(call.args) >= 3:
            size = call.args[2]
        if isinstance(size, (ast.List, ast.Tuple)):
            return size.elts
    return None


def _is_placeholder(node, base: int) -> bool:
    return (
        isinstance(node, ast.Constant)
        and isinstance(node.value, int)
        and not isinstance(node.value, bool)
        and node.value == base
    )


def _find_get_inputs(tree: ast.Module) -> ast.FunctionDef | None:
    """Return the last module-level ``def get_inputs`` (the one KernelBook ships)."""
    found = None
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == "get_inputs":
            found = node
    return found


def _input_ranks(func: ast.FunctionDef) -> list[int]:
    """Ranks (dim counts) of every recognizable tensor shape inside ``get_inputs``."""
    ranks = []
    for call in ast.walk(func):
        if isinstance(call, ast.Call):
            elts = _shape_elts(call)
            if elts is not None:
                ranks.append(len(elts))
    return ranks


def _scale_get_inputs(python_code: str, cfg: ScaleConfig) -> tuple[str, int]:
    """Rewrite placeholder dims in ``get_inputs`` and return (new_source, target_S).

    ``target_S`` is the per-row uniform scale (== ``cfg.placeholder`` when nothing was
    scaled), so the caller can apply the same value to ``get_init_inputs``. Only the
    ``get_inputs`` function text is reformatted; the rest of ``python_code`` is left
    byte-for-byte intact by splicing on line spans.
    """
    if cfg.mode == "off":
        return python_code, cfg.placeholder

    tree = ast.parse(python_code)
    func = _find_get_inputs(tree)
    if func is None:
        return python_code, cfg.placeholder

    ranks = _input_ranks(func)
    if not ranks:
        return python_code, cfg.placeholder
    target = cfg.target_for_rank(max(ranks))

    for call in ast.walk(func):
        if not isinstance(call, ast.Call):
            continue
        elts = _shape_elts(call)
        if elts is None:
            continue
        for i, e in enumerate(elts):
            if not _is_placeholder(e, cfg.placeholder):
                continue
            if cfg.mode == "batch-only":
                if i == 0:
                    elts[i] = ast.Constant(cfg.batch_target)
            else:  # uniform
                elts[i] = ast.Constant(target)

    ast.fix_missing_locations(func)
    new_func_src = ast.unparse(func)

    lines = python_code.splitlines()
    spliced = lines[: func.lineno - 1] + new_func_src.splitlines() + lines[func.end_lineno :]
    new_code = "\n".join(spliced)
    if python_code.endswith("\n"):
        new_code += "\n"
    # In batch-only mode init args are never touched (feature dims unchanged).
    init_target = cfg.placeholder if cfg.mode == "batch-only" else target
    return new_code, init_target


def _scale_value(v, base: int, target: int):
    """Scale a single init literal: placeholder ints -> target, everything else as-is."""
    if isinstance(v, bool):
        return v
    if isinstance(v, int) and v == base:
        return target
    return v


def _is_valid_identifier(name: str) -> bool:
    return bool(name) and name.isidentifier()


def _literalizable(value) -> bool:
    """True if ``value`` round-trips through repr / ast.literal_eval.

    Only plain literals (ints, floats, str, bool, None, and lists/tuples/dicts
    thereof) qualify — anything else (tensors, custom objects) forces the
    runtime-bake fallback.
    """
    try:
        return ast.literal_eval(repr(value)) == value
    except Exception:
        return False


def _normalize_init(raw) -> tuple[list, dict]:
    """Normalize KernelBook ``get_init_inputs()`` output to ``(args, kwargs)``.

    KernelBook returns ``[args_list, kwargs_dict]`` but a few rows return a plain
    positional list — handle both.
    """
    if (
        isinstance(raw, (list, tuple))
        and len(raw) == 2
        and isinstance(raw[0], (list, tuple))
        and isinstance(raw[1], dict)
    ):
        return list(raw[0]), dict(raw[1])
    if isinstance(raw, (list, tuple)):
        return list(raw), {}
    raise ConversionError(f"unexpected get_init_inputs() shape: {type(raw).__name__}")


def _flatten_to_positional(cls, args: list, kwargs: dict):
    """Return an all-positional arg list equivalent to ``cls(*args, **kwargs)``.

    Returns ``None`` when the call cannot be expressed positionally (``*args`` /
    ``**kwargs`` inits, or a defaulted param skipped before a later supplied one).
    """
    try:
        sig = inspect.signature(cls.__init__)
        bound = sig.bind(_SELF, *args, **kwargs)
    except (TypeError, ValueError):
        return None

    positional = []
    for name, p in sig.parameters.items():
        if name == "self":
            continue
        if p.kind in (p.VAR_POSITIONAL, p.VAR_KEYWORD):
            if bound.arguments.get(name):  # actually used → not expressible positionally
                return None
            continue
        positional.append(bound.arguments.get(name, _MISSING))

    while positional and positional[-1] is _MISSING:  # trailing defaults are fine to drop
        positional.pop()
    if any(x is _MISSING for x in positional):  # interior gap → not positional
        return None
    return positional


def convert_row(python_code: str, module_name: str, scale: ScaleConfig | None = None) -> str:
    """Return KernelBench-style source for one KernelBook row.

    Strategy (A): when the original init is expressible as pure positional
    literals, alias ``Model = <module_name>`` and emit a flat-positional
    ``get_init_inputs()`` — byte-compatible with a hand-written KernelBench
    problem. Aliasing (rather than renaming the class body) keeps any internal
    ``super(<module_name>, self)`` references valid.

    Strategy (B) fallback: keep the original class verbatim and add a no-arg
    ``Model`` subclass that bakes the captured args/kwargs, with
    ``get_init_inputs()`` returning ``[]``. Robust for non-literal init args.

    When ``scale`` is given, KernelBook's placeholder dims (the magic ``4``) are
    up-scaled to GPU-meaningful sizes in *both* ``get_inputs`` and the emitted
    ``get_init_inputs``, by one per-row factor so the shapes stay mutually
    consistent. ``scale=None`` reproduces the original (tiny-input) behaviour.
    """
    if not _is_valid_identifier(module_name):
        raise ConversionError(f"module_name {module_name!r} is not a valid identifier")
    if not re.search(rf"\bclass\s+{re.escape(module_name)}\b", python_code):
        raise ConversionError(f"class {module_name!r} not found in python_code")

    # Execute the original to read its declared init inputs.
    ns: dict = {}
    try:
        exec(compile(python_code, "<kernelbook_row>", "exec"), ns)
    except Exception as e:  # noqa: BLE001 - surface any import/exec failure to caller
        raise ConversionError(f"python_code failed to exec: {e}") from e

    if "get_init_inputs" not in ns:
        raise ConversionError("python_code does not define get_init_inputs()")
    if "get_inputs" not in ns:
        raise ConversionError("python_code does not define get_inputs()")
    if module_name not in ns:
        raise ConversionError(f"{module_name!r} not defined after exec")

    args, kwargs = _normalize_init(ns["get_init_inputs"]())

    # Up-scale the runtime input shapes; `init_target` is the matching per-row scale
    # to apply to the model's init dims so coupling (feature dim == input dim) holds.
    init_target = (scale.placeholder if scale else 4)
    if scale is not None:
        try:
            python_code, init_target = _scale_get_inputs(python_code, scale)
        except SyntaxError as e:  # malformed row source — leave inputs un-scaled
            raise ConversionError(f"could not parse python_code for scaling: {e}") from e
    base = scale.placeholder if scale else init_target

    # Strategy A: flatten the init to all-positional literals (binding kwargs against
    # the __init__ signature) -> a native-looking KernelBench problem.
    flat = _flatten_to_positional(ns[module_name], args, kwargs)
    if flat is not None and all(_literalizable(a) for a in flat):
        flat = [_scale_value(a, base, init_target) for a in flat]
        positional = ", ".join(repr(a) for a in flat)
        return (
            python_code.rstrip()
            + _BANNER
            + f"Model = {module_name}\n\n"
            + "def get_init_inputs():\n"
            + f"    return [{positional}]\n"
        )

    # Strategy B: keep the original class and bake the captured args/kwargs into a
    # no-arg Model subclass, read at runtime so non-literal args (tensors, custom
    # objects) survive. `_kb_scale` rewrites placeholder dims to stay consistent with
    # the up-scaled get_inputs shapes; non-int values pass through untouched, and when
    # scaling is off (base == init_target) it is a no-op.
    return (
        python_code.rstrip()
        + _BANNER
        + f"_KB_BASE, _KB_TARGET = {base!r}, {init_target!r}\n\n"
        + "def _kb_scale(v):\n"
        + "    if isinstance(v, bool):\n"
        + "        return v\n"
        + "    if isinstance(v, int) and v == _KB_BASE:\n"
        + "        return _KB_TARGET\n"
        + "    if isinstance(v, (list, tuple)):\n"
        + "        return type(v)(_kb_scale(x) for x in v)\n"
        + "    if isinstance(v, dict):\n"
        + "        return {k: _kb_scale(x) for k, x in v.items()}\n"
        + "    return v\n\n"
        + "_kb_raw_init = get_init_inputs()\n"
        + "if (isinstance(_kb_raw_init, (list, tuple)) and len(_kb_raw_init) == 2\n"
        + "        and isinstance(_kb_raw_init[0], (list, tuple)) and isinstance(_kb_raw_init[1], dict)):\n"
        + "    _KB_ARGS, _KB_KWARGS = list(_kb_raw_init[0]), dict(_kb_raw_init[1])\n"
        + "else:\n"
        + "    _KB_ARGS, _KB_KWARGS = list(_kb_raw_init), {}\n"
        + "_KB_ARGS = [_kb_scale(a) for a in _KB_ARGS]\n"
        + "_KB_KWARGS = {k: _kb_scale(v) for k, v in _KB_KWARGS.items()}\n\n"
        + f"class Model({module_name}):\n"
        + "    def __init__(self):\n"
        + "        super().__init__(*_KB_ARGS, **_KB_KWARGS)\n\n"
        + "def get_init_inputs():\n"
        + "    return []\n"
    )


def _run_smoke_inproc(converted_src: str, device: str = "cuda") -> tuple[bool, str]:
    """Instantiate the converted ``Model`` and run one eager forward, in-process.

    Returns ``(ok, reason)``. This is the raw build+forward with no isolation:
    a pathological row (e.g. a multi-GiB weight tensor or a kernel that aborts)
    can OOM-kill or hard-crash the *calling* process. Use :class:`SmokeRunner`
    (or :func:`smoke_test`) to run it under a child process instead.
    """
    import torch  # local import so the converter is usable without torch present

    ns: dict = {}
    try:
        exec(compile(converted_src, "<converted>", "exec"), ns)
    except Exception as e:  # noqa: BLE001
        return False, f"exec failed: {e}"

    for required in ("Model", "get_inputs", "get_init_inputs"):
        if required not in ns:
            return False, f"missing {required}"

    def _to_device(obj):
        if isinstance(obj, torch.Tensor):
            return obj.to(device)
        if isinstance(obj, (list, tuple)):
            return type(obj)(_to_device(o) for o in obj)
        return obj

    try:
        init_inputs = ns["get_init_inputs"]()
        model = ns["Model"](*init_inputs).to(device)
        model.eval()
        inputs = _to_device(ns["get_inputs"]())
        with torch.no_grad():
            model(*inputs)
        if device != "cpu" and torch.cuda.is_available():
            torch.cuda.synchronize()  # surface async kernel errors here, not later
    except Exception as e:  # noqa: BLE001
        return False, f"forward failed: {type(e).__name__}: {e}"

    return True, ""


_WORKER_READY = "__ready__"


def _smoke_worker_loop(device, req_q, resp_q):  # pragma: no cover - child process
    """Persistent worker: warm torch/CUDA once, then service rows until told to stop."""
    try:
        import torch

        if device != "cpu" and torch.cuda.is_available():
            torch.zeros(1, device=device)  # pay CUDA-context init now, not per row
    except Exception:  # noqa: BLE001
        pass  # let the first real row surface any torch/device problem
    resp_q.put((_WORKER_READY, ""))
    while True:
        item = req_q.get()
        if item is None:  # shutdown sentinel
            return
        ok, reason = _run_smoke_inproc(item, device)
        resp_q.put((ok, reason))


class SmokeRunner:
    """Run :func:`_run_smoke_inproc` inside an isolated, restartable child process.

    Each row is evaluated in a long-lived ``spawn`` child so CUDA stays warm
    across rows. If a row OOM-kills the child, segfaults, hard-aborts inside a
    CUDA kernel, or simply hangs past ``timeout``, only the child dies: the
    parent records the failure as a normal ``(False, reason)`` skip and spins up
    a fresh child for the next row. This is what keeps one bad row (e.g. a conv
    whose hyper-params got up-scaled into a multi-GiB weight tensor) from taking
    down a whole ``--all`` conversion run.
    """

    # Generous one-off budget for spawning + importing torch + CUDA-context init,
    # kept separate from the per-row timeout so the first row isn't penalised.
    _STARTUP_TIMEOUT = 300.0

    def __init__(self, device: str = "cuda", timeout: float = 300.0):
        import multiprocessing as mp

        self.device = device
        self.timeout = timeout if timeout and timeout > 0 else None
        self._ctx = mp.get_context("spawn")
        self._proc = None
        self._req_q = None
        self._resp_q = None

    def _ensure_proc(self) -> None:
        import queue as _queue

        if self._proc is not None and self._proc.is_alive():
            return
        self._req_q = self._ctx.Queue()
        self._resp_q = self._ctx.Queue()
        self._proc = self._ctx.Process(
            target=_smoke_worker_loop,
            args=(self.device, self._req_q, self._resp_q),
            daemon=True,
        )
        self._proc.start()
        # Block until the worker has imported torch and warmed the device, so the
        # per-row deadline measures the actual build+forward, not startup cost.
        try:
            msg = self._resp_q.get(timeout=self._STARTUP_TIMEOUT)
        except _queue.Empty:
            msg = None
        if not (isinstance(msg, tuple) and msg and msg[0] == _WORKER_READY):
            # Worker failed to come up; subsequent run() will report the death.
            self._kill_proc()

    def _kill_proc(self) -> None:
        if self._proc is None:
            return
        if self._proc.is_alive():
            self._proc.terminate()
            self._proc.join(5)
            if self._proc.is_alive():
                self._proc.kill()
                self._proc.join()
        self._proc = None
        self._req_q = self._resp_q = None

    def run(self, converted_src: str) -> tuple[bool, str]:
        import queue as _queue

        self._ensure_proc()
        if self._proc is None:  # worker failed to start up
            return False, "worker failed to start (torch/CUDA init error)"
        self._req_q.put(converted_src)

        deadline = None if self.timeout is None else time.monotonic() + self.timeout
        while True:
            remaining = None if deadline is None else max(0.0, deadline - time.monotonic())
            try:
                return self._resp_q.get(timeout=1.0 if remaining is None else min(1.0, remaining))
            except _queue.Empty:
                if not self._proc.is_alive():
                    # Child died without answering: OOM-kill / segfault / CUDA abort.
                    ec = self._proc.exitcode
                    self._proc = None
                    self._req_q = self._resp_q = None
                    return False, _exit_reason(ec)
                if deadline is not None and time.monotonic() >= deadline:
                    self._kill_proc()
                    return False, f"timeout: exceeded {self.timeout:g}s (worker killed)"

    def close(self) -> None:
        if self._proc is not None and self._proc.is_alive() and self._req_q is not None:
            try:
                self._req_q.put(None)
                self._proc.join(5)
            except Exception:  # noqa: BLE001
                pass
        self._kill_proc()

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()


def _exit_reason(exitcode) -> str:
    """Human-readable reason for a worker that died without returning a result."""
    if exitcode is not None and exitcode < 0:
        sig = -exitcode
        try:
            name = signal.Signals(sig).name
        except ValueError:
            name = f"signal {sig}"
        hint = " (likely out-of-memory)" if sig in (signal.SIGKILL, signal.SIGABRT) else ""
        return f"worker died: killed by {name}{hint}"
    return f"worker died: exitcode={exitcode} (crash/OOM, no result)"


def smoke_test(
    converted_src: str, device: str = "cuda", timeout: float = 300.0
) -> tuple[bool, str]:
    """One-shot, process-isolated smoke test (convenience wrapper).

    Spawns a fresh child, runs a single row, and tears it down. For converting
    many rows, build one :class:`SmokeRunner` and reuse it so CUDA stays warm.
    """
    with SmokeRunner(device=device, timeout=timeout) as runner:
        return runner.run(converted_src)
