"""F1.7 -- the work is handed to a PyTorch compiler instead of a Triton kernel.

``torch.compile`` / ``torch.jit.script`` / TorchDynamo will happily generate the
kernel for the model. That is a fallback wearing a hat.

Reference: fallback variant of F1.4; the broader anti-cheat taxonomy is in
SOL-ExecBench (NVIDIA, 2026, arXiv:2603.19173).
"""

from __future__ import annotations

from ....core.model import Finding, ModuleModel
from .. import register

#: Exact offloader names -- matched literally, never by prefix. `str.startswith` swept in
#: every longer name in these namespaces: `torch.compile` caught the whole `torch.compiler.*`
#: namespace (`torch.compiler.disable` *opts out* of compilation), and `torch.jit.script`
#: caught `torch.jit.script_if_tracing` (a no-op outside tracing) -- see BUG-21.
OFFLOAD_EXACT = frozenset({"torch.compile", "torch.jit.script", "torch.jit.trace"})

#: Whole namespaces that are compilation machinery -- matched on a dot boundary so
#: `torch._dynamo.optimize` hits but a hypothetical `torch._dynamox` would not.
OFFLOAD_NAMESPACES = ("torch._dynamo", "torch._inductor")


def _is_offload(name: str) -> bool:
    if name in OFFLOAD_EXACT:
        return True
    return any(name == ns or name.startswith(ns + ".") for ns in OFFLOAD_NAMESPACES)


@register("F1.7", "compile_offload", "fail")
def check(model: ModuleModel) -> list[Finding]:
    # Not restricted to reachable code: a @torch.compile decorator runs at class
    # definition time and still routes the computation away from Triton.
    hits = [(c.qualname, c.lineno) for c in model.host_calls if _is_offload(c.qualname)]
    if not hits:
        return []

    listed = ", ".join(f"`{q}` (line {ln})" for q, ln in hits)
    return [
        Finding(
            check_id="F1.7",
            severity="fail",
            message=(
                f"The solution delegates compilation to PyTorch: {listed}. The kernel "
                f"must be written explicitly in Triton, not generated by torch.compile "
                f"or TorchScript."
            ),
            data={"ops": sorted({q for q, _ in hits}), "lineno": min(ln for _, ln in hits)},
        )
    ]
